netbox-plugin/netbox_user/urls.py
from django.urls import include,path
from . import models, views
from netbox.views.generic import ObjectChangeLogView


urlpatterns = (
    # User list
    path('plugin-user/', views.UserListListView.as_view(), name='userlist_list'),
    path('plugin-user/add/', views.UserListEditView.as_view(), name='userlist_add'),
    path('plugin-user/<int:pk>/', views.UserListView.as_view(), name='userlist'),

    #### User List BULK
	path('plugin-user/edit/', views.UserListBulkEditView.as_view(), name='userlist_bulk_edit'),
	path('plugin-user/delete/', views.UserListBulkDeleteView.as_view(), name='userlist_bulk_delete'),

    path('plugin-user/<int:pk>/edit/', views.UserListEditView.as_view(), name='userlist_edit'),
    path('plugin-user/<int:pk>/delete/', views.UserListDeleteView.as_view(), name='userlist_delete'),

    path('plugin-user/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='userlist_changelog', kwargs={
        'model': models.UserList
    }),

    # User list rules
    path('rules/', views.UserListRuleListView.as_view(), name='resourceaccess_list'),
    path('rules/add/', views.UserListRuleEditView.as_view(), name='resourceaccess_add'),
    path('rules/<int:pk>/', views.UserListRuleView.as_view(), name='pluginuserrule'),
    
    #### Rules BULK
    path('rules/edit/', views.UserListRuleBulkEditView.as_view(), name='resourceaccess_bulk_edit'),
	path('rules/delete/', views.UserListRuleBulkDeleteView.as_view(), name='resourceaccess_bulk_delete'),

    path('rules/<int:pk>/edit/', views.UserListRuleEditView.as_view(), name='resourceaccess_edit'),
    path('rules/<int:pk>/delete/', views.UserListRuleDeleteView.as_view(), name='resourceaccess_delete'),

    path('rules/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='resourceaccess_changelog', kwargs={
        'model': models.ResourceAccess
    }),


    # Resources 
    path('resources/', views.ResourcesListListView.as_view(), name='resources_list'),
    path('resources/add/', views.ResourcesListEditView.as_view(), name='resources_add'),
    path('resources/<int:pk>/', views.ResourcesView.as_view(), name='resourceslist'),

    #### Resources BULK
    path('resources/edit/', views.ResourcesBulkEditView.as_view(), name='resources_bulk_edit'),
    path('resources/delete/', views.ResourcesBulkDeleteView.as_view(), name='resources_bulk_delete'),

    path('resources/<int:pk>/edit/', views.ResourcesListEditView.as_view(), name='resources_edit'),
    path('resources/<int:pk>/delete/', views.ResourcesListDeleteView.as_view(), name='resources_delete'),

    path('resources/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='resources_changelog', kwargs={
        'model': models.Resources
    }),


    # environment 
    path('environment/', views.EnvironmentListListView.as_view(), name='environment_list'),
    path('environment/add/', views.EnvironmentListEditView.as_view(), name='environment_add'),
    path('environment/<int:pk>/', views.EnvironmentView.as_view(), name='environmentlist'),

    #### Environment BULK
    path('environment/edit/', views.EnvironmentBulkEditView.as_view(), name='environment_bulk_edit'),
    path('environment/delete/', views.EnvironmentBulkDeleteView.as_view(), name='environment_bulk_delete'),

    path('environment/<int:pk>/edit/', views.EnvironmentListEditView.as_view(), name='environment_edit'),
    path('environment/<int:pk>/delete/', views.EnvironmentListDeleteView.as_view(), name='environment_delete'),

    path('environment/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='environment_changelog', kwargs={
        'model': models.Environment
    }),

    # group 
    path('group/', views.GroupListListView.as_view(), name='groups_list'),
    path('group/add/', views.GroupListEditView.as_view(), name='groups_add'),
    path('group/<int:pk>/', views.GroupView.as_view(), name='groupslist'),


    #### Group BULK
    path('group/edit/', views.GroupListBulkEditView.as_view(), name='groups_bulk_edit'),
    path('group/delete/', views.GroupListBulkDeleteView.as_view(), name='groups_bulk_delete'),

    path('group/<int:pk>/edit/', views.GroupListEditView.as_view(), name='groups_edit'),
    path('group/<int:pk>/delete/', views.GroupListDeleteView.as_view(), name='groups_delete'),

    path('group/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='groups_changelog', kwargs={
        'model': models.Groups
    }),
	
    path('groups/', views.GroupView.as_view(), name='groups-list'),
    
	
	

    # Approver 
    path('approver/', views.ApproverListListView.as_view(), name='approver_list'),
    path('approver/add/', views.ApproverListEditView.as_view(), name='approver_add'),
    path('approver/<int:pk>/', views.ApproverView.as_view(), name='approverlist'),

    #### Approver BULK
    path('approver/edit/', views.ApproverBulkEditView.as_view(), name='approver_bulk_edit'),
    path('approver/delete/', views.ApproverBulkDeleteView.as_view(), name='approver_bulk_delete'),

    path('approver/<int:pk>/edit/', views.ApproverListEditView.as_view(), name='approver_edit'),
    path('approver/<int:pk>/delete/', views.ApproverListDeleteView.as_view(), name='approver_delete'),

    path('approver/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='approver_changelog', kwargs={
        'model': models.Approver
    }),
	

    # Sector 
    path('sector/', views.SectorListListView.as_view(), name='sector_list'),
    path('sector/add/', views.SectorListEditView.as_view(), name='sector_add'),
    path('sector/<int:pk>/', views.SectorView.as_view(), name='sectorlist'),

    #### Sector BULK
    path('sector/edit/', views.SectorBulkEditView.as_view(), name='sector_bulk_edit'),
    path('sector/delete/', views.SectorBulkDeleteView.as_view(), name='sector_bulk_delete'),

    path('sector/<int:pk>/edit/', views.SectorListEditView.as_view(), name='sector_edit'),
    path('sector/<int:pk>/delete/', views.SectorListDeleteView.as_view(), name='sector_delete'),

    path('sector/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='sector_changelog', kwargs={
        'model': models.Sector
    }),
	

    # resource groups 
    path('resourcegroups/', views.ResourceGroupsListListView.as_view(), name='resourcegroups_list'),
    path('resourcegroups/add/', views.ResourceGroupsListEditView.as_view(), name='resourcegroups_add'),
    path('resourcegroups/<int:pk>/', views.ResourceGroupsView.as_view(), name='resourcegroups'),
 
    #### Resources Groups BULK
	path('resourcegroups/edit/', views.ResourceGroupsBulkEditView.as_view(), name='resourcegroups_bulk_edit'),
	path('resourcegroups/delete/', views.ResourceGroupsBulkDeleteView.as_view(), name='resourcegroups_bulk_delete'),
	
    path('resourcegroups/<int:pk>/edit/', views.ResourceGroupsListEditView.as_view(), name='resourcegroups_edit'),
    path('resourcegroups/<int:pk>/delete/', views.ResourceGroupsListDeleteView.as_view(), name='resourcegroups_delete'),

    path('resourcegroups/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='resourcegroups_changelog', kwargs={
        'model': models.ResourceGroups
    }),	
)


netbox-plugin/netbox_user/models.py
from django.db import models
from netbox.models import NetBoxModel

from utilities.choices import ChoiceSet
from django.urls import reverse # type: ignore
from django.db.models import Max
from extras.models import Tag
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver



class Resources(NetBoxModel):
    recurso = models.CharField(max_length=100,unique=True, blank=True)
    comments = models.TextField(blank=True)
    
    clone_fields = (
        'tags',
    )
    class Meta:
        ordering = ('recurso',)
        verbose_name = "Recurso"

    def __str__(self):
        return self.recurso
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_user:resourceslist', args=[self.pk])
    
    def clone(self):
        attrs = super().clone()
        attrs['extra-value'] = 123
        return attrs


class Environment(NetBoxModel):
    ambiente = models.CharField(max_length=100,unique=True, blank=True)
    comments = models.TextField(blank=True)

    clone_fields = (
        'tags',
    )

    class Meta:
        ordering = ('ambiente', )
        verbose_name = "Ambiente"

    def __str__(self):
        return self.ambiente
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_user:environmentlist', args=[self.pk])
    
    def clone(self):
        attrs = super().clone()
        attrs['extra-value'] = 123
        return attrs


class Approver(NetBoxModel):
    aprovador = models.CharField(max_length=100,unique=True, blank=True)
    comments = models.TextField(blank=True)

    clone_fields = (
        'tags',
    )
    class Meta:
        ordering = ('aprovador', )
        verbose_name = "Aprovador"

    def __str__(self):
        return self.aprovador
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_user:approverlist', args=[self.pk])
    
    def clone(self):
        attrs = super().clone()
        attrs['extra-value'] = 123
        return attrs


class Sector(NetBoxModel):
    setor = models.CharField(max_length=100,unique=True, blank=True)
    comments = models.TextField(blank=True)

    clone_fields = (
        'tags',
    )

    class Meta:
        ordering = ('setor',)
        verbose_name = "Setore"

    def __str__(self):
        return str(self.setor)
    
    def get_absolute_url(self):
        return reverse('plugins:netbox_user:sectorlist', args=[self.pk])
    
    def clone(self):
        attrs = super().clone()
        attrs['extra-value'] = 123
        return attrs





class ActionChoicesStatusUserColor(ChoiceSet):
    key = 'UserList.status_user'

    CHOICES = [
        ('active', 'Active', 'green'),
        ('deactivate', 'Deactivate', 'red'),
    ]
class ActionChoicesSetor(ChoiceSet):
    key = 'UserList.setor'

    CHOICES = [
        ('infraestutura', 'Infraestutura',),
        ('desenvolvimento', 'Desenvolvimento'),
        ('administrativo', 'Administrativo'),
    ]
class ActionChoices(ChoiceSet):
    CHOICES = [
        ('active', 'Active', 'green'),
        ('expired', 'Expired', 'red'),
    ]

class ActionChoicesPeriodo(ChoiceSet):
    key = 'ResourceAccess.periodo'
    CHOICES = [
        ('permanente', 'Permanente', 'yellow'),
        ('temporario', 'Temporário', 'purple'),
    ]

class ActionChoicesType(ChoiceSet):
    key = 'ResourceAccess.tipo_acesso'

    CHOICES = [
        ('leitura', 'Leitura', 'purple'),
        ('leituraescrita', 'Leitura e Escrita', 'purple'),
    ]


# Modelo para grupos
class Groups(NetBoxModel):
    grupo = models.CharField(max_length=100, unique=True, blank=True,)
    comments = models.TextField(blank=True)

    clone_fields = (
         'tags',
    )

    class Meta:
        ordering = ('grupo', )
        verbose_name = "Grupo"

    def __str__(self):
        return self.grupo

    def get_absolute_url(self):
        return reverse('plugins:netbox_user:groupslist', args=[self.pk])
    
    def clone(self):
        attrs = super().clone()
        attrs['extra-value'] = 123
        return attrs



# Modelo para o usuário
class UserList(NetBoxModel):
    name = models.CharField(max_length=100,unique=True)
    comments = models.TextField(blank=True)

    groups = models.ManyToManyField(Groups,blank=True, related_name='users', through='UserGroupAssociation')

    tags = models.ManyToManyField(Tag, blank=True)
    
    setor = models.ManyToManyField(Sector, blank=True, related_name='users')

    status_user = models.CharField(
        max_length=30,
        choices=ActionChoicesStatusUserColor._choices,
        verbose_name="Status User",
        default='active'
    )
    
    clone_fields = (
        'tags','status_user', 'setor',
    )


    class Meta:
        ordering = ('name',)
        verbose_name = "Usuário"

    def __str__(self):
        return self.name
    
    def get_related_groups(self):
        return self.groups.all()

    def get_absolute_url(self):
        return reverse('plugins:netbox_user:userlist', args=[self.pk])

    def get_status_user_color(self):
        return ActionChoicesStatusUserColor.colors.get(self.status_user)
    
    def total_resources_count(self):
        user_resources_count = ResourceAccess.objects.filter(user=self).count() 
        group_resources_count = ResourceGroups.objects.filter(groupslist__in=self.groups.all()).count()

        return user_resources_count + group_resources_count
    
    def save(self, *args, **kwargs):
        # Salva o usuário normalmente
        super().save(*args, **kwargs)
        
    def get_group_association_date(self, group):
        try:
            association = self.group_associations.get(group=group)
            return association.data_associacao
        except UserGroupAssociation.DoesNotExist:
            return None
        
    def clone(self):
        attrs = super().clone()
        attrs['extra-value'] = 123
        return attrs



class ResourceAccess(NetBoxModel):
    user = models.ForeignKey(
        to=UserList,
        on_delete=models.CASCADE,
        related_name='rules',
        blank=True
    )

    periodo = models.CharField(
        max_length=30,
        choices=ActionChoicesPeriodo._choices,
    )

    index = models.IntegerField()

    comments = models.TextField(blank=True)

    action = models.CharField(
        max_length=30,
        blank=True
    )

    tipo_acesso = models.CharField(
        choices=ActionChoicesType._choices,
        blank=True
    )

    data_concessao = models.DateField(blank=True)
    data_expiracao = models.DateField(blank=True, null=True)

    justificativa = models.TextField(blank=True)

    recurso = models.ForeignKey(
        to=Resources,
        on_delete=models.CASCADE,
        related_name='rules',
        blank=True
    )

    aprovador = models.ForeignKey(
        to=Approver,
        on_delete=models.CASCADE,
        related_name='rules',
        blank=True
    )

    ambiente = models.ManyToManyField(Environment, blank=True)

    status = models.CharField(
        max_length=30,
        choices=ActionChoices._choices,
        blank=True
    )

    clone_fields = (
        'recurso', 'tipo_acesso', 'aprovador', 'status','ambiente','tags'
    )

    prerequisite_models = (
        'netbox_user.Environment',
        'netbox_user.Approver',
    )

    class Meta:
        ordering = ('user', 'index')
        verbose_name = "Recursos dos Usuário"

        unique_together = ('user', 'recurso')

    def __str__(self):
        return self.recurso.recurso
    
    def get_status_color(self):
        return ActionChoices.colors.get(self.status)

    def get_tipo_acesso_color(self):
        return ActionChoicesType.colors.get(self.tipo_acesso)
    
    def get_periodo_color(self):
        return ActionChoicesPeriodo.colors.get(self.periodo)
    

    def get_absolute_url(self):
        return reverse('plugins:netbox_user:pluginuserrule', args=[self.pk])
    
    def save(self, *args, **kwargs):
        if self.index is None:
            last_index = ResourceAccess.objects.filter(user=self.user).aggregate(Max('index'))['index__max']
            self.index = (last_index or 0) + 1  
        super().save(*args, **kwargs)

    def clean(self):
        
        if self.data_concessao and self.data_expiracao:
            if self.data_concessao > self.data_expiracao:
                raise ValidationError({
                    'data_concessao': 'A data de concessão não pode ser maior que a data de expiração.'
                })
        if not self.data_expiracao:  
            if self.periodo != 'permanente': 
                raise ValidationError({
                    'periodo': 'Quando a data de expiração está vazia, o período deve ser permanente.'
                })
        else:  
            if self.periodo != 'temporario':
                raise ValidationError({
                    'periodo': 'Quando a data de expiração é preenchida, o período deve ser temporário.'
                })

        super().clean()

class ResourceGroups(NetBoxModel):
    index = models.IntegerField()

    groupslist = models.ForeignKey(
        to=Groups,
        on_delete=models.CASCADE,
        related_name='resource_group_rules'
    )

    recurso = models.ForeignKey(
        to=Resources,
        on_delete=models.CASCADE,
        related_name='resource_group_rules'
    )

    tipo_acesso = models.CharField(
        choices=ActionChoicesType._choices,
        blank=True
    )

    aprovador = models.ForeignKey(
        to=Approver,
        on_delete=models.CASCADE,
        related_name='resource_aprovador'

netbox-plugin/netbox_user/templates/netbox_user/approver.html
{% extends 'generic/object.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Infos</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Aprovador</th>
              <td>{{ object }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      

      {% include 'inc/panels/comments.html' %} 
    </div>
  </div>
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/environment.html
{% extends 'generic/object.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Infos</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Ambiente</th>
              <td>{{ object }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      

      {% include 'inc/panels/comments.html' %} 
    </div>
  </div>
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/groups.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% load helpers %}
{% load i18n %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Infos</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Grupo</th>
              <td>{{ object }}</td>
            </tr>

            <tr>
              <th scope="row">Recursos</th>
              <td>{{ object.resource_group_rules.count }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">

      {% include 'inc/panels/comments.html' %} 
      {% include 'inc/panels/related_objects.html'%}
      
    </div>
  </div>


  <div class="row">
    <div class="col col-md-12">
      <div class="card p-2">
        <h5 class="card-header">Recursos</h5>
        <div class="card-body table-responsive">
            {% render_table groups %}
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/resourceaccess.html
{% extends 'generic/object.html' %}


{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Permissões</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Usuário</th>
              <td>
                <a href="{{ object.user.get_absolute_url }}">{{ object.user }}</a>
              </td>
            </tr>

            <tr>
              <th scope="row">Setor</th>
              <td>
                {% for setor in object.user.setor.all %}
                  <a href="{{ setor.get_absolute_url }}">{{ setor.setor }} {% if setor.exists %}{{ setor.all|join:", " }}{% endif %}</a>
                {% endfor %}
                
                <a href="{{ object.user.name.get_absolute_url }}"> </a>
              </td>
            </tr>
            
            <tr>
              <th scope="row">Tipo de Acesso</th>
              <td>{{ object.get_tipo_acesso_display|capfirst }}</td>
            </tr>
            <tr>
              <th scope="row">Data Concessão</th>
              <td>{{ object.data_concessao|date:"d/m/Y" }}</td>
            </tr>
            <tr>
              <th scope="row">Data Expiração</th>
              <td>{{ object.data_expiracao|date:"d/m/Y" }}</td>
            </tr>
            <tr>
              <th scope="row">Aprovador</th>
              <td>
                {{ object.aprovador }}
              </td>
            </tr>
            <tr>
              <th scope="row">Periodo</th>
              <td>{{ object.periodo|capfirst }}</td>
            </tr>
            <tr>
              <th scope="row">Ambiente</th>
              <td>
                {% if object.ambiente.exists %}
                {{ object.ambiente.all|join:", " }}
                {% endif %}
            </td>
            </tr>

          </table>
        </div>

      </div>
      {% include 'inc/panels/custom_fields.html' %}


    </div>
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Campo Texto</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
              <th scope="row">Justificativa</th>
              <td>{{ object.justificativa }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/comments.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
  </div>
  
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/resourcegroups.html
{% extends 'generic/object.html' %}
{% include 'generic/object_list.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Permissões</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Grupo</th>
              <td>
                <a href="{{ object.groupslist.get_absolute_url }}">{{ object.groupslist }}</a>
              </td>

            </tr>
            
            <tr>
              <th scope="row">Tipo de Acesso</th>
              <td>{{ object.tipo_acesso|capfirst }}</td>
            </tr>

            <tr>
              <th scope="row">Aprovador</th>
              <td>
                {{ object.aprovador }}
              </td>
            </tr>
            <tr>
              <th scope="row">Ambiente</th>
              <td>
                {% if object.ambiente.exists %}
                {{ object.ambiente.all|join:", " }}
                {% endif %}
            </td>
            </tr>

          </table>
        </div>

      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}



    </div>
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Campo Texto</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
              <th scope="row">Justificativa</th>
              <td>{{ object.justificativa }}</td>
            </tr>
          </table>
        </div>
      </div>

      {% include 'inc/panels/comments.html' %}
    </div>
  </div>
  
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/resources.html
{% extends 'generic/object.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Infos</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Recurso</th>
              <td>{{ object }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      

      {% include 'inc/panels/comments.html' %} 
    </div>
  </div>
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/sector.html
{% extends 'generic/object.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Infos</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Setor</th>
              <td>{{ object }}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
    <div class="col col-md-6">
      

      {% include 'inc/panels/comments.html' %} 
      {% include 'inc/panels/related_objects.html'%}
    </div>
  </div>
{% endblock content %}

netbox-plugin/netbox_user/templates/netbox_user/userlist.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Recursos</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Usuário</th>
              <td>{{ object.name }}</td>
            </tr>

            <tr>
              <th scope="row">Recursos do usuário</th>
              <td>{{ object.rules.count }}</td>
            </tr>
            <tr>
              <th scope="row" >Status do usuário</th>
              <td>{{ object.status_user|capfirst }}</td>
            </tr>

            <tr>
              <th scope="row" >Grupo</th>
              <td>
                {% if object.groups.exists %}
                {% for grupo in object.groups.all %}
                  <a href="{{ grupo.get_absolute_url }}">{{ grupo }}</a>{% if not forloop.last %} | {% endif %}
                {% endfor %}
                {% endif %}
              </td>
            </tr>

            <th scope="row">Setor</th>
            <td>
              {% if object.setor.exists %}
                {% for setor in object.setor.all %}
                  <a href="{{ setor.get_absolute_url }}">{{ setor }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
              {% endif %}
            </td>
          </table>
        </div>
      </div>
      {% include 'inc/panels/comments.html' %}
      {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}


      {% if user_group_associations %}
      <div class="col-md-12 card p-2 mt-4">
        <h5 class="card-header">Associações do Usuário com Grupos</h5>
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Grupo</th>
                <th>Data de Associação</th>
              </tr>
            </thead>
            <tbody>
              {% for association in user_group_associations %}
                <tr>
                  <td>
                    <a href="{{ association.group.get_absolute_url }}">{{ association.group }}</a>
                  </td>
                  <td>{{ association.data_associacao|date:"d/m/Y" }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    {% endif %}

    </div>
  </div>

<div class="row">
  <div class="col col-md-12">
    <div class="card p-2">
      <h5 class="card-header">Recursos</h5>
      <div class="card-body table-responsive">
          {% render_table recurso %}
      </div>
    </div>
  </div>
</div>





{% if object.groups.exists %}
<div class="row">
  <div class="col pt-4 col-md-12">
    <div class="card p-2">
      <h5 class="card-header">Recursos do grupo</h5>
      <div class="card-body table-responsive">
        {% render_table recurso_grupo %}
      </div>
    </div>
  </div>
</div>
{% endif %}





{% endblock content %}